# Generated by Django 4.2.12 on 2024-05-09 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='fields',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fields'),
        ),
    ]
